# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-25 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20190825_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=90),
        ),
    ]
