# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-25 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20190825_1648'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categories',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categories',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
